name: lr-pav
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake=7.18.1
  - biopython=1.78
  - intervaltree=3.1.0
  - matplotlib=3.5.1
  - matplotlib-venn=0.11.5
  - numpy=1.22.3
  - pandas=1.5.0
  - pysam=0.19.1
  - scipy=1.7.3
